services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./models:/app/models
      - ./line-sft:/app/line-sft
      - ./html:/app/html

